name: imagecaptcha
description: Image captcha generator written in Dart.
version: 1.0.0
homepage: https://github.com/ailabs-software/dart-image-captcha
author: Sheyenne York <support@shopwindow.io>

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  image: any

